#!/bin/bash
if [[ `whoami` -eq 'root' ]]; then
    cd ~
    systemctl systemctl set-default multi-user.target
    pacman -S --noconfirm networkmanager reflector
    systemctl enable NetworkManager; systemctl start NetworkManager
    
    reflector --verbose --latest 5 --sort rate --save /etc/pacman.d/mirrorlist
    pacman -S --noconfirm python ansible git openssh
    systemctl enable sshd; systemctl start sshd
    git clone https://github.com/kewlfft/ansible-aur.git ~/.ansible/plugins/modules/aur
    git clone https://github.com/Dqicool/ansible_desktop.git
	read -r -p "wayland sway? [Y/n], otherwise X i3 " response
	if [[ $response =~ ^(yes|y| ) ]] || [[ -z $response ]]; then
        ansible-playbook ansible_desktop/playbooks/waylandSway.yml
    else
        ansible-playbook ansible_desktop/playbooks/Xi3.yml
	fi
else
    echo "please run this script with root"
fi
