
---
- hosts: localhost
  connection: local
  become: true
  tasks:
    - include_tasks: tasks/PkgIns/pacman_cache_update.yml
    - include_tasks: tasks/PkgIns/pacman.yml
    - include_tasks: tasks/PkgIns/install_paru.yml
