
  - name: add family group
    group:
      name: family
      state: present
      gid: 1000
  
  - name: add 1000 qidong in wheel family and docker
    user:
      name: qidong
      shell: /bin/bash
      state: present
      groups: family,wheel,docker,video
      append: yes
      uid: 1000
      create_home: yes

  - name: git config for qidong
    copy:
      src: ../../files/gitconfig
      dest: /home/qidong/.gitconfig
      owner: qidong
      group: family
      mode: '0644'
    become: yes
    become_user: qidong

