- name: Install packages
  flatpak:
    name: com.microsoft.Teams
    state: present
    method: user
    remote: flathub
  become: yes
  become_user: qidong

- name: Install packages
  flatpak:
    name: org.libreoffice.LibreOffice
    state: present
    method: user
    remote: flathub
  become: yes
  become_user: qidong

- name: Install packages
  flatpak:
    name: com.valvesoftware.Steam
    state: present
    method: user
    remote: flathub
  become: yes
  become_user: qidong

- name: Install packages
  flatpak:
    name: org.videolan.VLC
    state: present
    method: user
    remote: flathub
  become: yes
  become_user: qidong

- name: Install packages
  flatpak:
    name: com.skype.Client
    state: present
    method: user
    remote: flathub
  become: yes
  become_user: qidong

- name: Install packages
  flatpak:
    name: org.gimp.GIMP
    state: present
    method: user
    remote: flathub
  become: yes
  become_user: qidong