task: # Install trizen using makepkg, skip if it is already installed
  - aur: name=paru use=makepkg state=present
    become: yes
    become_user: aur_builder
  # Install package_name_1 and package_name_2 using yay
  - aur:
    use: paru
    name:
      - ttf-iosevka
      - ttf-iosevka-slab
      - ttf-iosevka-term-slab
      - ttf-iosevka-term
      - breeze-default-cursor-theme
      - mailspring
      - wayvnc