# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.local/bin:$PATH
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5 #0.84375

#restore default emacs keybinding
bindkey -e

# Basic history 
HISTFILE=~/.cache/zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

#up line search
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

#source plugin manager
source /usr/share/zsh/share/antigen.zsh 
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
#antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zpm-zsh/ls

antigen apply

#themeing
eval "$(starship init zsh)"

#alias
pls() {
	sudo `history -1 | awk '{print $2}'`
}

#additional
bindkey "\e[3~" delete-char
