  # Install package_name_1 and package_name_2 using yay
  - name: yay cvmfs pkg
    kewlfft.aur.aur:
      use: yay
      name: cvmfs
    become: yes
    become_user: aur_builder

  - name: copy cvmfs config
    copy:
      src: ../files/fstab_cvmfs
      dest: /root/fstab_cvmfs
      owner: root
      group: wheel
      mode: '0644'

  - name: Ensures /cvmfs/atlas.cern.ch  dir exists
    file: path=/cvmfs/atlas.cern.ch  state=directory
  
  - name: Ensures /cvmfs/atlas-condb.cern.ch  dir exists
    file: path=/cvmfs/atlas-condb.cern.ch  state=directory

  - name: Ensures /cvmfs/unpacked.cern.ch dir exists
    file: path=/cvmfs/unpacked.cern.ch  state=directory

  - name: Ensures /cvmfs/sft.cern.ch  dir exists
    file: path=/cvmfs/sft.cern.ch  state=directory

  - name: Ensures /cvmfs/atlas-nightlies.cern.ch  dir exists
    file: path=/cvmfs/atlas-nightlies.cern.ch  state=directory

  - name: append cvmfs to fstab
    shell: if cat /etc/fstab | grep cvmfs; then echo "done"; else cat /root/fstab_cvmfs >> /etc/fstab; fi;

  - name: etc cvmfs def.loacl change to atlas
    shell: sed -i -e 's/CVMFS_REPOSITORIES=atlas.cern.ch,atlas-condb.cern.ch,grid.cern.ch,sft.cern.ch,lhcb.cern.ch,lhcbdev.cern.ch/CVMFS_REPOSITORIES=atlas.cern.ch,atlas-condb.cern.ch,atlas-nightlies.cern.ch,sft.cern.ch,unpacked.cern.ch/' /etc/cvmfs/default.local

  - name: remove tmp files
    file: 
      path: /root/fstab_cvmfs
      state: absent