
---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    # update first
    - include_tasks: ../tasks/Maintinance/rebuild_keys.yml
    - include_tasks: ../tasks/Maintinance/pacman_syu.yml
    - include_tasks: ../tasks/Cli/timesyncd.yml

    # system utils
    - include_tasks: ../tasks/Drivers/sys_utils.yml
    - include_tasks: ../tasks/Drivers/qemu-ga.yml

    #cli utils
    - include_tasks: ../tasks/Cli/cli_utils.yml
    #user qidong
    - include_tasks: ../tasks/Users/qidong.yml

    # drivers 
    - include_tasks: ../tasks/Drivers/yay.yml
    - include_tasks: ../tasks/Drivers/nvidia.yml
    - include_tasks: ../tasks/Drivers/flatpak.yml

    # remote file system 
    - include_tasks: ../tasks/FileSys/nfs.yml



    #user cli specific
    - include_tasks: ../tasks/Cli/root.yml
    - include_tasks: ../tasks/Cli/zsh.yml

    #WM
    - include_tasks: ../tasks/WMs/sway.yml

    #gui apps
    - name: include all gui apps
      include_tasks: "{{ item }}"
      with_fileglob: 
        - ../tasks/Gui/apps/*.yml
        - ../tasks/Gui/utils/*.yml
    
    #cleanup
    - include_tasks: ../tasks/CleanUp/delAURbuilder.yml